app = "remix-turso-multitenant"
primary_region = "sin"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/resources/healthcheck"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
