# fly.toml app configuration file generated for remix-turso-multitenant-frosty-silence-7089 on 2024-04-17T08:50:02+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remix-turso-multitenant-frosty-silence-7089'
primary_region = 'sin'

[build]

[deploy]
  release_command = 'pnpm drizzle:migrate'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/resources/healthcheck'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
